---
-
  name: Dogecoin
  ticker: DOGE
-
  name: Bitcoin
  ticker: BTC
-
  name: Litecoin
  ticker: LTC
-
  name: Alphacoin
  ticker: ALF
-
  name: Americancoin
  ticker: AMC
-
  name: Anoncoin
  ticker: ANC
-
  name: Argentum
  ticker: ARG
-
  name: Betacoin
  ticker: BET
-
  name: BBQCoin
  ticker: BQC
-
  name: Bitbar
  ticker: BTB
-
  name: Bytecoin
  ticker: BTE
-
  name: Bitgem
  ticker: BTG
-
  name: Cryptobuck
  ticker: BUK
-
  name: Bottlecaps
  ticker: CAP
-
  name: Catcoin
  ticker: CAT
-
  name: CryptogenicBullion
  ticker: CGB
-
  name: CopperLark
  ticker: CLR
-
  name: Cosmoscoin
  ticker: CMC
-
  name: CHNCoin
  ticker: CNC
-
  name: CraftCoin
  ticker: CRC
-
  name: CasinoCoin
  ticker: CSC
-
  name: eMark
  ticker: DEM
-
  name: DigitalCoin
  ticker: DGC
-
  name: Diamond
  ticker: DMD
-
  name: ElaCoin
  ticker: ELC
-
  name: Emerald
  ticker: EMD
-
  name: FireflyCoin
  ticker: FFC
-
  name: FreiCoin
  ticker: FBC
-
  name: Franko
  ticker: FRK
-
  name: FastCoin
  ticker: FST
-
  name: FeatherCoin
  ticker: FTC
-
  name: GrandCoin
  ticker: GDC
-
  name: Globalcoin
  ticker: GLC
-
  name: GoldCoin
  ticker: GLD
-
  name: Galaxycoin
  ticker: GLX
-
  name: HoboNickels
  ticker: HBN
-
  name: IXCoin
  ticker: IXC
-
  name: KrugerCoin
  ticker: KGC
-
  name: Lucky7Coin
  ticker: LK7
-
  name: LuckyCoin
  ticker: LKY
-
  name: LottoCoin
  ticker: LOT
-
  name: MegaCoin
  ticker: MEC
-
  name: MinCoin
  ticker: MNC
-
  name: Nibble
  ticker: NBL
-
  name: NeoCoin
  ticker: NEC
-
  name: Netcoin
  ticker: NET
-
  name: NameCoin
  ticker: NMC
-
  name: NoirBits
  ticker: NRB
-
  name: NovaCoin
  ticker: NVC
-
  name: Orbitcoin
  ticker: ORB
-
  name: PhilosopherStone
  ticker: PHS
-
  name: Peercoin
  ticker: PPC
-
  name: ProtoShares
  ticker: PTS
-
  name: PhoenixCoin
  ticker: PXC
-
  name: PayCoin
  ticker: PYC
-
  name: QuarkCoin
  ticker: QRK
-
  name: StableCoin
  ticker: SBC
-
  name: Spots
  ticker: SPT
-
  name: Securecoin
  ticker: SRC
-
  name: Tagcoin
  ticker: TAG
-
  name: TekCoin
  ticker: TEK
-
  name: TigerCoin
  ticker: TGC
-
  name: TerraCoin
  ticker: TRC
-
  name: Unobtanium
  ticker: UNO
-
  name: WorldCoin
  ticker: WDC
-
  name: JouleCoin
  ticker: XJO
-
  name: PrimeCoin
  ticker: XPM
-
  name: YBCoin
  ticker: YBC
-
  name: ZetaCoin
  ticker: ZET
-
  name: AndroidsToken
  ticker: ADT
-
  name: AsicCoin
  ticker: ASC
-
  name: Pennies
  ticker: CENT
-
  name: CopperBars
  ticker: CPR
-
  name: Doubloons
  ticker: DBL
-
  name: DevCoin
  ticker: DVC
-
  name: ElephantCoin
  ticker: ELP
-
  name: EZCoin
  ticker: EZC
-
  name: FlorinCoin
  ticker: FLO
-
  name: GameCoin
  ticker: GME
-
  name: InfinieCoin
  ticker: IFC
-
  name: JunkCoin
  ticker: JKC
-
  name: MemeCoin
  ticker: MEM
-
  name: MasterCoin
  ticker: MST
-
  name: RedCoin
  ticker: RED
-
  name: RoyalCoin
  ticker: RYC
-
  name: SexCoin
  ticker: SXC
-
  name: Tickets
  ticker: TIX
-
  name: XenCoin
  ticker: XNC
