development:
  adapter: postgresql
  encoding: unicode
  database: such_coin_wow_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: such_coin_wow_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: such_coin_wow_production
  pool: 5
